theme: jekyll-theme-midnight
title: Daniel Wood
description: Welcome to my personal Github page.
permalink: /blog/:year/:month/:day/:title
repository: danielkylewood/danielkylewood.github.io
plugins:
  - jekyll-sitemap